config/routes.rb
Rails.application.routes.draw do
 root 'pics#index'

 devise_for :users
 resources :pics

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pic.rb
class Pic < ApplicationRecord
	validates :title, presence: true
	#validates :image, presence: true
	belongs_to :user
	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pics, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

  before_action :authenticate_user!, except: %i[index show]

  before_action :set_pic, only: %i[show edit update destroy]

  def index
    @pics = Pic.all.order("created_at DESC")

  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: "Pic was sacessufuly created"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Pic successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path, notice: 'Pic was successfully deleted'
  end

  private

  def set_pic
    @pic = Pic.find(params[:id])
  end

  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Instagramm
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'



  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-brand= link_to "Instagramm", root_path    


        - if user_signed_in? 
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Gram It!", new_pic_path
            %li= link_to "Settings", edit_user_registration_path
            %li= link_to "Sign_out", destroy_user_session_path, method: :delete

        - else 
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "Join", new_user_registration_path
            %li= link_to "Log in", new_user_session_path

    .container
      -flash.each do |name,msg|
        =content_tag :div, msg, class: "alert alert-info"


      = yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
	- if @pic.errors.any?
		#errors
		%h2 
		= pluralize(@pic.errors.count, "error")
		preventes this Pic from saving
		%ul
		- @pic.errors.full_messages.each do |msg|
			%li = msg 

	.form-group 
		= f.input :title, input_html: { class: 'form-control' }
	.form-group 
		= f.input :image, input_html: { class: 'form-control' }	
	.form-group
		= f.input :description, input_html: {class: 'form-control' }

	= f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
 .row
  .panel.panel-defult
   .panel-heading
    %h1 Fix Pic
   .panel-body
    .current_image
     %strong.center Right Now
     = image_tag @pic.image, style: "width: 400px"
    = render 'form'
    = link_to 'Cancel', pic_path 

app/views/pics/index.html.haml
.col-md-6.col-md-offset-3
  #pics.transition-enabaled
    - @pics.each do |pic|
      .box.panel.panel-defaults
        = link_to (image_tag pic.image , style: "width: 150px")
        %h2= link_to pic.title, pic
 

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
 .row
  .panel.panel-defult
   .panel-heading
    %h1 Post Pic
   .panel-body
    = render 'form'
    = link_to 'Back', root_path 

app/views/pics/show.html.haml
#pic_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel.heading.pic_image
        = image_tag @pic.image

      .panel-body
        %h1= @pic.title
        %p= @pic.description

      .panel-footer
        .row
          .col-md-6
            %p.user
              - if current_user
                Picture by
                = @pic.user.email

          .col-md-6
            .btn-group.pull-right
              - if current_user
                = link_to 'Edit', edit_pic_path, class: "btn btn-info"
                = link_to 'Delete', pic_path, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"